In [3]:
import pandas as pd

In [4]:
orders = pd.read_csv("../Data/olist_orders_dataset.csv")
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [5]:
orders.shape
orders.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date'],
      dtype='str')

In [6]:
order_items = pd.read_csv("../Data/olist_order_items_dataset.csv")
payments = pd.read_csv("../Data/olist_order_payments_dataset.csv")
customers = pd.read_csv("../Data/olist_customers_dataset.csv")
products = pd.read_csv("../Data/olist_products_dataset.csv")
sellers = pd.read_csv("../Data/olist_sellers_dataset.csv")

In [11]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [12]:
df = orders.merge(customers, on="customer_id", how="left")
df.shape

(99441, 12)

In [13]:
df = df.merge(order_items, on="order_id", how="left")
df.shape

(113425, 18)

In [14]:
df = df.merge(payments, on="order_id", how="left")
df.shape

(118434, 22)

In [15]:
df = df.merge(products, on="product_id", how="left")
df.shape

(118434, 30)

In [16]:
df = df.merge(sellers, on="seller_id", how="left")
df.shape

(118434, 33)

In [17]:
df.head()
df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state'],
      dtype='str')

In [18]:
df.drop_duplicates(inplace=True)
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 176
order_delivered_carrier_date     2074
order_delivered_customer_date    3397
order_estimated_delivery_date       0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
order_item_id                     830
product_id                        830
seller_id                         830
shipping_limit_date               830
price                             830
freight_value                     830
payment_sequential                  3
payment_type                        3
payment_installments                3
payment_value                       3
product_category_name            2528
product_name_lenght              2528
product_description_lenght       2528
product_photos_qty               2528
product_weight_g                  850
product_length_cm                 850
product_height_cm                 850
product_width_cm                  850
seller_zip_code_prefix            830
seller_city                       830
seller_state                      830
dtype: int64

In [19]:
df["Revenue"] = df["price"] + df["freight_value"]
df["Cost"] = 0.65 * df["price"] + df["freight_value"]
df["Profit"] = df["Revenue"] - df["Cost"]
df["Discount"] = df["Revenue"] - df["payment_value"]

In [21]:
df.to_csv("C:/Users/wrick/OneDrive/Desktop/Dynamic-Pricing-Project/master_dataset.csv", index=False)

In [22]:
df.shape

(118434, 37)

In [23]:
df.columns

Index(['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp',
       'order_approved_at', 'order_delivered_carrier_date',
       'order_delivered_customer_date', 'order_estimated_delivery_date',
       'customer_unique_id', 'customer_zip_code_prefix', 'customer_city',
       'customer_state', 'order_item_id', 'product_id', 'seller_id',
       'shipping_limit_date', 'price', 'freight_value', 'payment_sequential',
       'payment_type', 'payment_installments', 'payment_value',
       'product_category_name', 'product_name_lenght',
       'product_description_lenght', 'product_photos_qty', 'product_weight_g',
       'product_length_cm', 'product_height_cm', 'product_width_cm',
       'seller_zip_code_prefix', 'seller_city', 'seller_state', 'Revenue',
       'Cost', 'Profit', 'Discount'],
      dtype='str')

In [24]:
df[["Revenue", "Cost", "Profit", "Discount"]].head()

   Revenue      Cost   Profit  Discount
0    38.71   28.2135  10.4965     20.59
1    38.71   28.2135  10.4965     36.71
2    38.71   28.2135  10.4965     20.12
3   141.46   99.9150  41.5450      0.00
4   179.12  123.1550  55.9650      0.00

In [25]:
df.describe()

,customer_zip_code_prefix,order_item_id,price,freight_value,payment_sequential,payment_installments,payment_value,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_zip_code_prefix,Revenue,Cost,Profit,Discount
count,118434.000000,117604.000000,117604.000000,117604.000000,118431.000000,118431.000000,118431.000000,115906.000000,115906.000000,115906.000000,117584.000000,117584.000000,117584.00000,117584.000000,117604.000000,117604.000000,117604.000000,117604.000000,1.176010e+05
mean,35034.264392,1.195920,120.822849,20.045551,1.094207,2.937398,172.849395,48.767208,786.957302,2.207849,2114.281067,30.256872,16.63029,23.068394,24442.886483,140.868400,98.580403,42.287997,-3.181598e+01
std,29819.290218,0.697721,184.477367,15.861351,0.728290,2.774164,268.259831,10.035162,653.029009,1.719519,3788.754048,16.190874,13.45878,11.748372,27573.802989,191.616461,127.325414,64.567079,1.792709e+02
min,1003.000000,1.000000,0.850000,0.000000,1.000000,0.000000,0.000000,5.000000,4.000000,1.000000,0.000000,7.000000,2.00000,6.000000,1001.000000,6.080000,4.540000,0.297500,-1.195607e+04
25%,11310.000000,1.000000,39.900000,13.080000,1.000000,1.000000,60.860000,42.000000,347.000000,1.000000,300.000000,18.000000,8.00000,15.000000,6429.000000,55.270000,41.093500,13.965000,-7.105427e-15
50%,24240.000000,1.000000,74.900000,16.290000,1.000000,2.000000,108.200000,52.000000,601.000000,1.000000,700.000000,25.000000,13.00000,20.000000,13660.000000,92.115000,66.053500,26.215000,0.000000e+00
75%,58464.500000,1.000000,134.900000,21.190000,1.000000,4.000000,189.245000,57.000000,985.000000,3.000000,1800.000000,38.000000,20.00000,30.000000,28035.000000,157.780000,110.336250,47.215000,0.000000e+00
max,99990.000000,21.000000,6735.000000,409.680000,29.000000,24.000000,13664.080000,76.000000,3992.000000,20.000000,40425.000000,105.000000,105.00000,118.000000,99730.000000,6929.310000,4572.060000,2357.250000,3.899000e+03

In [26]:
df.isnull().sum()

order_id                            0
customer_id                         0
order_status                        0
order_purchase_timestamp            0
order_approved_at                 176
order_delivered_carrier_date     2074
order_delivered_customer_date    3397
order_estimated_delivery_date       0
customer_unique_id                  0
customer_zip_code_prefix            0
customer_city                       0
customer_state                      0
order_item_id                     830
product_id                        830
seller_id                         830
shipping_limit_date               830
price                             830
freight_value                     830
payment_sequential                  3
payment_type                        3
payment_installments                3
payment_value                       3
product_category_name            2528
product_name_lenght              2528
product_description_lenght       2528
product_photos_qty               2528
product_weight_g                  850
product_length_cm                 850
product_height_cm                 850
product_width_cm                  850
seller_zip_code_prefix            830
seller_city                       830
seller_state                      830
Revenue                           830
Cost                              830
Profit                            830
Discount                          833
dtype: int64

In [27]:
df[["Revenue", "Cost", "Profit"]].sum()

Revenue    1.656669e+07
Cost       1.159345e+07
Profit     4.973238e+06
dtype: float64

In [28]:
df["Profit"].sum() / df["Revenue"].sum()

np.float64(0.3001950550185159)

In [29]:
df.groupby("product_category_name")["Profit"].sum().sort_values(ascending=False).head(10)

product_category_name
beleza_saude              454121.7695
relogios_presentes        438600.1550
cama_mesa_banho           382392.8570
esporte_lazer             358398.7190
informatica_acessorios    329797.1495
moveis_decoracao          267782.8615
utilidades_domesticas     233305.4500
cool_stuff                231808.3215
automotivo                215863.3785
ferramentas_jardim        181376.1390
Name: Profit, dtype: float64

In [30]:
df.groupby("product_category_name")["Profit"].sum().sort_values().head(10)

product_category_name
seguros_e_servicos                99.1515
fashion_roupa_infanto_juvenil    199.4475
cds_dvds_musicais                255.5000
casa_conforto_2                  270.6095
flores                           388.5140
fraldas_higiene                  548.6565
pc_gamer                         586.5790
artes_e_artesanato               634.9035
fashion_esporte                  741.8285
la_cuisine                       806.3930
Name: Profit, dtype: float64

In [31]:
df["Discount"].describe()

count    1.176010e+05
mean    -3.181598e+01
std      1.792709e+02
min     -1.195607e+04
25%     -7.105427e-15
50%      0.000000e+00
75%      0.000000e+00
max      3.899000e+03
Name: Discount, dtype: float64